---
- name: Custom .bashrc file
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    backup: yes
    state: present
    block: |
        # Show git branch in prompt
        parse_git_branch() {
            git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
        }
        export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "

        # Utils
        alias grepy="grep -r --include='*.py'"

        # Others
        alias gitmoji="google-chrome https://gitmoji.dev"
        alias shrug='echo "¯\_(ツ)_/¯"'
