---
- name: Install Terminator
  apt:
    name: terminator
    state: present
    update_cache: yes
  become: yes

- name: Install tree
  apt:
    name: tree
    state: present
    update_cache: yes
  become: yes

- name: Install Unzip
  apt:
    name: unzip
    state: present
    update_cache: yes
  become: yes

# Requires pipx. Available in pipx.yml
- name: Install or upgrade csvkit
  shell:
      cmd: "{{ system_python3_dir }} -m pipx install csvkit"
  ignore_errors: yes

